### ISSUE TITLE
UUID empty on first run on ios9, true device

### ISSUE THREAD

**Issue by monxas** [Paldom/UniqueDeviceID#18]
When I first run this code  (simplified for reading purposes) after an install on true device, I get a blank uuid. On second run it does work though.

Iphone 5s ios9 on my side.

[testuuid.txt](https://github.com/Paldom/UniqueDeviceID/files/53996/testuuid.txt)

**Comment by bau720123** [comment]
can't understand what your true mean
please use the simple code to see if wverytime will get the uuid
```
// Get UUID
window.plugins.uniqueDeviceID.get(success, fail);
Success callback function:

function success(uuid)
{
    console.log(uuid);
};
```

if yes，I think it is the "testuuid.txt" problem

**Comment by kostia-official** [comment]
+1 
same issue on iPhone 6 (9.2) and iPhone 5s (8.3)
