### ISSUE TITLE
Is there a way to get different unique device IDs in two separate applications?

### ISSUE THREAD

**Issue by Sobiru** [Paldom/UniqueDeviceID#24]
Let's say I have two applications on a device and both of them are using this plugin. As of now, when I call `window.plugins.uniqueDeviceID.get()`, both of them return the same ID. My issue is that I don't want to duplicate my existing user tables for the second app so both apps are using the same tables and this is a problem as users in the first app are already recognized by that ID. Is there a way for each application to get their own unique device IDs?

**Comment by Ziao** [comment]
Why can't you just do window.plugins.uniqueDeviceID.get() + "app1" and window.plugins.uniqueDeviceID.get() + "app2"?

**Comment by kashban** [comment]
Use getVendorId(). This is uniqe on a per app basis.
