### ISSUE TITLE
what's the difference between by phonegap itself "device.uuid"

### ISSUE THREAD

**Issue by bau720123** [Paldom/UniqueDeviceID#5]
the plugin is work perfect
so I just want to ask
what's the difference between by phonegap itself "device.uuid"
according to this
https://github.com/apache/cordova-plugin-device/blob/c6e23d8a61793c263443794d66d40723b4d04377/doc/index.md

for example my ASUS Zenfone A500KL
phonegap itself device.uuid = > 9ea488bd-..........-03361
your plugin's uuid = > 9ea488bd-..........-20328

**Comment by Paldom** [comment]
cordova-plugin-device uses AndroidID which has some problem (not always unique). This plugin uses a combo of android id, device id and sim id.

**Comment by bau720123** [comment]
got it
thanks @Paldom

**Comment by erikbarz** [comment]
Does the generated UUID change, when the operating system is being updated?
