### ISSUE TITLE
Getting Undefined Instead of Device UDID in ios.

### ISSUE THREAD

**Issue by Neotrixsx** [Paldom/UniqueDeviceID#8]
I am new in Phonegap ios Application Development, My application have Push notication Function for that i need Device UDUI, so I use your Plugin in my Application But I get Undefine in UDID Option.

Please Help Me.

**Comment by Paldom** [comment]
Hi,
could you please give more details on this issue?

**Comment by Neotrixsx** [comment]
Thanks For Reply, I did some mistake in codeing. this time I get Application UDID in iOS.
